apxs support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar P3S build build_cpu build_vendor build_os host host_cpu host_vendor host_os RANLIB ac_ct_RANLIB YACC CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE commentcharset_windows1251 commentcharset_windows1250 commentcharset_windows1257 commentcharset_koi8r dll_extension mysql_client pgsql_client oracle_client sqlite_client CPP_LIBS GC_LIBS PCRE_INCLUDES PCRE_LIBS XML_INCLUDES XML_LIBS CURL_INCLUDES MIME_INCLUDES MIME_LIBS APACHE13 COMPILE_APACHE13_MODULE_TRUE COMPILE_APACHE13_MODULE_FALSE INCLTDL LIBLTDL subdirs LIBADD_DL CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar P3S build build_cpu build_vendor build_os host host_cpu host_vendor host_os RANLIB ac_ct_RANLIB YACC CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE commentcharset_windows1251 commentcharset_windows1250 commentcharset_windows1257 commentcharset_koi8r dll_extension mysql_client pgsql_client oracle_client sqlite_client CPP_LIBS GC_LIBS PCRE_INCLUDES PCRE_LIBS XML_INCLUDES XML_LIBS CURL_INCLUDES MIME_INCLUDES MIME_LIBS APACHE APACHE_INC APACHE_CFLAGS COMPILE_APACHE_MODULE_TRUE COMPILE_APACHE_MODULE_FALSE INCLTDL LIBLTDL subdirs LIBADD_DL CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -907,9 +907,8 @@ Optional Packages:
   \"--with-sendmail=COMMAND\" forces this command to send mail.
                           example: \"--with-sendmail=/usr/sbin/sendmail -t\"
                           (makes parser ignore user-defined sendmail commands)
-  --with-apache13=D       D is the Apache13 source distribution directory
-                          builds library for apache_module using that dir
-                          (do not add /src)
+  --with-apache=FILE is the full path for APXS
+                          builds apache DSO module using apxs
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -4142,7 +4141,7 @@ fi;
 if test "${with_static_gc+set}" = set; then
   withval="$with_static_gc"
 
-	GC_LIBS="-L$withval -Wl,-Bstatic -l$GC_LIB_NAME -Wl,-Bdynamic"
+	GC_LIBS="$withval/lib$GC_LIB_NAME.a"
 
 fi;
 if test -z "$GC_LIBS"; then
@@ -4434,26 +4433,41 @@ fi;
 
 
 
-# Check whether --with-apache13 or --without-apache13 was given.
-if test "${with_apache13+set}" = set; then
-  withval="$with_apache13"
-  APACHE13=$withval
-	if test \! -f "$APACHE13/src/include/httpd.h"; then
-		{ { echo "$as_me:$LINENO: error: $APACHE13 does not seem to be valid Apache13 source distribution directory" >&5
-echo "$as_me: error: $APACHE13 does not seem to be valid Apache13 source distribution directory" >&2;}
+# Check whether --with-apache or --without-apache was given.
+if test "${with_apache+set}" = set; then
+  withval="$with_apache"
+
+	APXS=$withval
+
+	if test -z "$APXS" -o "$APXS" = "yes"; then
+		APXS=`which apxs 2>/dev/null`
+	fi;
+
+	APACHE=`$APXS -q TARGET 2>/dev/null`
+
+	if test -z "$APACHE"; then
+		{ { echo "$as_me:$LINENO: error: $APXS does not seem to be valid apache apxs utility path" >&5
+echo "$as_me: error: $APXS does not seem to be valid apache apxs utility path" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+
+	APACHE_MAIN_INC=`$APXS -q INCLUDEDIR`
+	APACHE_EXTRA_INC=`$APXS -q EXTRA_INCLUDES 2>/dev/null`
+	APACHE_INC="-I$APACHE_MAIN_INC $APACHE_EXTRA_INC"
+	APACHE_CFLAGS=`$APXS -q CFLAGS`
 
 fi;
 
 
 
-if test -n "$APACHE13"; then
-  COMPILE_APACHE13_MODULE_TRUE=
-  COMPILE_APACHE13_MODULE_FALSE='#'
+
+
+if test -n "$APACHE"; then
+  COMPILE_APACHE_MODULE_TRUE=
+  COMPILE_APACHE_MODULE_FALSE='#'
 else
-  COMPILE_APACHE13_MODULE_TRUE='#'
-  COMPILE_APACHE13_MODULE_FALSE=
+  COMPILE_APACHE_MODULE_TRUE='#'
+  COMPILE_APACHE_MODULE_FALSE=
 fi
 
 
@@ -7555,7 +7569,7 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
           ac_config_headers="$ac_config_headers src/include/pa_config_auto.h"
 
-                                                                                                                                                                                                                                                                                                                      ac_config_files="$ac_config_files Makefile src/Makefile src/types/Makefile src/classes/Makefile src/include/Makefile src/main/Makefile src/sql/Makefile src/lib/Makefile src/lib/gd/Makefile src/lib/smtp/Makefile src/lib/gc/Makefile src/lib/gc/include/Makefile src/lib/pcre/Makefile src/lib/cord/Makefile src/lib/cord/include/Makefile src/lib/cord/include/private/Makefile src/lib/ltdl/Makefile src/lib/md5/Makefile src/lib/sdbm/Makefile src/lib/sdbm/apr-include/Makefile src/lib/json/Makefile src/targets/Makefile src/targets/cgi/Makefile src/targets/apache13core/Makefile src/targets/apache13/Makefile src/targets/apache13/p3runConfigure src/targets/isapi/Makefile etc/Makefile etc/parser3.charsets/Makefile bin/Makefile bin/auto.p.dist"
+                                                                                                                                                                                                                                                                                                  ac_config_files="$ac_config_files Makefile src/Makefile src/types/Makefile src/classes/Makefile src/include/Makefile src/main/Makefile src/sql/Makefile src/lib/Makefile src/lib/gd/Makefile src/lib/smtp/Makefile src/lib/gc/Makefile src/lib/gc/include/Makefile src/lib/pcre/Makefile src/lib/cord/Makefile src/lib/cord/include/Makefile src/lib/cord/include/private/Makefile src/lib/ltdl/Makefile src/lib/md5/Makefile src/lib/sdbm/Makefile src/lib/sdbm/apr-include/Makefile src/lib/json/Makefile src/targets/Makefile src/targets/cgi/Makefile src/targets/apache/Makefile src/targets/isapi/Makefile etc/Makefile etc/parser3.charsets/Makefile bin/Makefile bin/auto.p.dist"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -7668,10 +7682,10 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${COMPILE_APACHE13_MODULE_TRUE}" && test -z "${COMPILE_APACHE13_MODULE_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"COMPILE_APACHE13_MODULE\" was never defined.
+if test -z "${COMPILE_APACHE_MODULE_TRUE}" && test -z "${COMPILE_APACHE_MODULE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COMPILE_APACHE_MODULE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"COMPILE_APACHE13_MODULE\" was never defined.
+echo "$as_me: error: conditional \"COMPILE_APACHE_MODULE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -8142,9 +8156,7 @@ do
   "src/lib/json/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/lib/json/Makefile" ;;
   "src/targets/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/targets/Makefile" ;;
   "src/targets/cgi/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/targets/cgi/Makefile" ;;
-  "src/targets/apache13core/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/targets/apache13core/Makefile" ;;
-  "src/targets/apache13/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/targets/apache13/Makefile" ;;
-  "src/targets/apache13/p3runConfigure" ) CONFIG_FILES="$CONFIG_FILES src/targets/apache13/p3runConfigure" ;;
+  "src/targets/apache/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/targets/apache/Makefile" ;;
   "src/targets/isapi/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/targets/isapi/Makefile" ;;
   "etc/Makefile" ) CONFIG_FILES="$CONFIG_FILES etc/Makefile" ;;
   "etc/parser3.charsets/Makefile" ) CONFIG_FILES="$CONFIG_FILES etc/parser3.charsets/Makefile" ;;
@@ -8311,9 +8323,11 @@ s,@XML_LIBS@,$XML_LIBS,;t t
 s,@CURL_INCLUDES@,$CURL_INCLUDES,;t t
 s,@MIME_INCLUDES@,$MIME_INCLUDES,;t t
 s,@MIME_LIBS@,$MIME_LIBS,;t t
-s,@APACHE13@,$APACHE13,;t t
-s,@COMPILE_APACHE13_MODULE_TRUE@,$COMPILE_APACHE13_MODULE_TRUE,;t t
-s,@COMPILE_APACHE13_MODULE_FALSE@,$COMPILE_APACHE13_MODULE_FALSE,;t t
+s,@APACHE@,$APACHE,;t t
+s,@APACHE_INC@,$APACHE_INC,;t t
+s,@APACHE_CFLAGS@,$APACHE_CFLAGS,;t t
+s,@COMPILE_APACHE_MODULE_TRUE@,$COMPILE_APACHE_MODULE_TRUE,;t t
+s,@COMPILE_APACHE_MODULE_FALSE@,$COMPILE_APACHE_MODULE_FALSE,;t t
 s,@INCLTDL@,$INCLTDL,;t t
 s,@LIBLTDL@,$LIBLTDL,;t t
 s,@subdirs@,$subdirs,;t t
